### ISSUE TITLE
packager.py gives error on execution !!!

### ISSUE THREAD

**Issue by raviprasad239** [Juniper/contrail-packaging#421]
I am trying to create contrail packages as per wiki " ./packager.py --build-id 01 --sku kilo".
But I am getting following error messages : 
packager@contrail-packaging:~/contrail-packaging/build$ ./packager.py --build-id 01 --sku kilo
grep: /home/packager/contrail-packaging/build/.repo/manifest.xml: No such file or directory
cat: /home/packager/contrail-packaging/build/controller/src/base/version.info: No such file or directory
Traceback (most recent call last):
  File "./packager.py", line 360, in <module>
    main()
  File "./packager.py", line 307, in main
    args.parse()
  File "./packager.py", line 158, in parse
    self.is_dir_exists(ns_cliargs.cache_base_dir)
  File "./packager.py", line 56, in is_dir_exists
    raise RuntimeError('Directory (%s) does not exists' %dirname)
RuntimeError: Directory (/cs-shared/builder/cache) does not exists
packager@contrail-packaging:~/contrail-packaging/build$

----------------------------------------------------------------------------------------
Please let me know : 
1) Do I need to 1st download contrail and openstack source code before running  "packager.py" ?
2) Can we use "packager.py" to package pre-compiled Opencontrail + Devstack build. ?

**Comment by aaryabhatt** [comment]
Did you find a way, how to resolve thiss or create contrail-install rpm package with this.

**Comment by fclaudiopalmeira** [comment]
I´ve tried both inside and outside of the sandbox and i had no luck...the exact same erros still occurs.
Does anyone have solution for this issue?
